<a href="https://colab.research.google.com/github/ariyapooh/People_parquet/blob/main/people.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import pyarrow.dataset as ds
import pyarrow.compute as pc

In [ ]:
from google.colab import drive
drive.mount('/content/drive') #ระวังเครื่องหมาย ‘ กับ ' ต่างกันนะคะ

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
path = '/content/drive/MyDrive/people-2000000.csv'
dfp = pd.read_csv(path) ## Dataset is now stored in a Pandas Dataframe
dfp

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,4defE49671cF860,Sydney,Shannon,Male,tvang@example.net,574-440-1423x9799,2020-07-09,Technical brewer
1,2,F89B87bCf8f210b,Regina,Lin,Male,helen14@example.net,001-273-664-2268x90121,1909-06-20,"Teacher, adult education"
2,3,Cad6052BDd5DEaf,Pamela,Blake,Female,brent05@example.org,927-880-5785x85266,1964-08-19,Armed forces operational officer
3,4,e83E46f80f629CD,Dave,Hoffman,Female,munozcraig@example.org,001-147-429-8340x608,2009-02-19,Ship broker
4,5,60AAc4DcaBcE3b6,Ian,Campos,Female,brownevelyn@example.net,166-126-4390,1997-10-02,Media planner
...,...,...,...,...,...,...,...,...,...
1999995,1999996,AbBE4F3Eb5df843,Susan,Ellison,Male,yward@example.net,855.222.4135x62040,1913-01-05,Research scientist (maths)
1999996,1999997,e71af3E8De63CDF,Cole,Sherman,Female,nbarnett@example.org,(130)829-9159x800,1977-04-15,Marketing executive
1999997,1999998,fAF0618097acD1B,Ethan,Leonard,Male,brett57@example.com,514.898.2376x3069,1960-08-14,Photographer
1999998,1999999,f1FC3346F68DFAb,Jordan,Waller,Female,harveykendra@example.com,6920274656,1911-09-05,Chartered accountant
1999999,2000000,B04Bb8bE7DA70ba,Shelley,Meza,Female,gamblejohnny@example.net,+1-765-874-1874,1961-11-30,Printmaker

In [ ]:
df.to_parquet('people.parquet')

In [ ]:
df

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,4defE49671cF860,Sydney,Shannon,Male,tvang@example.net,574-440-1423x9799,2020-07-09,Technical brewer
1,2,F89B87bCf8f210b,Regina,Lin,Male,helen14@example.net,001-273-664-2268x90121,1909-06-20,"Teacher, adult education"
2,3,Cad6052BDd5DEaf,Pamela,Blake,Female,brent05@example.org,927-880-5785x85266,1964-08-19,Armed forces operational officer
3,4,e83E46f80f629CD,Dave,Hoffman,Female,munozcraig@example.org,001-147-429-8340x608,2009-02-19,Ship broker
4,5,60AAc4DcaBcE3b6,Ian,Campos,Female,brownevelyn@example.net,166-126-4390,1997-10-02,Media planner
...,...,...,...,...,...,...,...,...,...
1999995,1999996,AbBE4F3Eb5df843,Susan,Ellison,Male,yward@example.net,855.222.4135x62040,1913-01-05,Research scientist (maths)
1999996,1999997,e71af3E8De63CDF,Cole,Sherman,Female,nbarnett@example.org,(130)829-9159x800,1977-04-15,Marketing executive
1999997,1999998,fAF0618097acD1B,Ethan,Leonard,Male,brett57@example.com,514.898.2376x3069,1960-08-14,Photographer
1999998,1999999,f1FC3346F68DFAb,Jordan,Waller,Female,harveykendra@example.com,6920274656,1911-09-05,Chartered accountant
1999999,2000000,B04Bb8bE7DA70ba,Shelley,Meza,Female,gamblejohnny@example.net,+1-765-874-1874,1961-11-30,Printmaker

In [ ]:
table = pa.Table.from_pandas(df)
print(table)
table = table.drop(["User Id","Email","Phone"])
print(table)

pyarrow.Table
Index: int64
User Id: string
First Name: string
Last Name: string
Sex: string
Email: string
Phone: string
Date of birth: string
Job Title: string
----
Index: [[1,2,3,4,5,...,1999996,1999997,1999998,1999999,2000000]]
User Id: [["4defE49671cF860","F89B87bCf8f210b","Cad6052BDd5DEaf","e83E46f80f629CD","60AAc4DcaBcE3b6",...,"AbBE4F3Eb5df843","e71af3E8De63CDF","fAF0618097acD1B","f1FC3346F68DFAb","B04Bb8bE7DA70ba"]]
First Name: [["Sydney","Regina","Pamela","Dave","Ian",...,"Susan","Cole","Ethan","Jordan","Shelley"]]
Last Name: [["Shannon","Lin","Blake","Hoffman","Campos",...,"Ellison","Sherman","Leonard","Waller","Meza"]]
Sex: [["Male","Male","Female","Female","Female",...,"Male","Female","Male","Female","Female"]]
Email: [["tvang@example.net","helen14@example.net","brent05@example.org","munozcraig@example.org","brownevelyn@example.net",...,"yward@example.net","nbarnett@example.org","brett57@example.com","harveykendra@example.com","gamblejohnny@example.net"]]
Phone: [["574-440-1423x9799","001-273-664-2268x90121","927-880-5785x85266","001-147-429-8340x608","166-126-4390",...,"855.222.4135x62040","(130)829-9159x800","514.898.2376x3069","6920274656","+1-765-874-1874"]]
Date of birth: [["2020-07-09","1909-06-20","1964-08-19","2009-02-19","1997-10-02",...,"1913-01-05","1977-04-15","1960-08-14","1911-09-05","1961-11-30"]]
Job Title: [["Technical brewer","Teacher, adult education","Armed forces operational officer","Ship broker","Media planner",...,"Research scientist (maths)","Marketing executive","Photographer","Chartered accountant","Printmaker"]]
pyarrow.Table
Index: int64
First Name: string
Last Name: string
Sex: string
Date of birth: string
Job Title: string
----
Index: [[1,2,3,4,5,...,1999996,1999997,1999998,1999999,2000000]]
First Name: [["Sydney","Regina","Pamela","Dave","Ian",...,"Susan","Cole","Ethan","Jordan","Shelley"]]
Last Name: [["Shannon","Lin","Blake","Hoffman","Campos",...,"Ellison","Sherman","Leonard","Waller","Meza"]]
Sex: [["Male","Male","Female","Female","Female",...,"Male","Female","Male","Female","Female"]]
Date of birth: [["2020-07-09","1909-06-20","1964-08-19","2009-02-19","1997-10-02",...,"1913-01-05","1977-04-15","1960-08-14","1911-09-05","1961-11-30"]]
Job Title: [["Technical brewer","Teacher, adult education","Armed forces operational officer","Ship broker","Media planner",...,"Research scientist (maths)","Marketing executive","Photographer","Chartered accountant","Printmaker"]]

In [ ]:
pq.write_to_dataset(table, root_path='my_parq', partition_cols=['Job Title'])

In [ ]:
# read partitioned table
table = pq.read_table('my_parq')
table.to_pandas().head()

    Index First Name  Last Name     Sex Date of birth           Job Title
0  131521    Kaitlyn     Baxter  Female    1943-09-24  Academic librarian
1  133596     Shelby  Henderson    Male    1919-06-15  Academic librarian
2  133800      Angel         Wu  Female    1991-02-20  Academic librarian
3  133935    Anthony      Haney  Female    2002-08-05  Academic librarian
4  134472      Henry   Hatfield  Female    1975-12-22  Academic librarian

In [ ]:
table.to_pandas()

,Index,First Name,Last Name,Sex,Date of birth,Job Title
0,131521,Kaitlyn,Baxter,Female,1943-09-24,Academic librarian
1,133596,Shelby,Henderson,Male,1919-06-15,Academic librarian
2,133800,Angel,Wu,Female,1991-02-20,Academic librarian
3,133935,Anthony,Haney,Female,2002-08-05,Academic librarian
4,134472,Henry,Hatfield,Female,1975-12-22,Academic librarian
...,...,...,...,...,...,...
1999995,1964579,Jaclyn,Lucas,Female,1946-05-10,Youth worker
1999996,1965049,Philip,Cooley,Female,1907-11-02,Youth worker
1999997,1965107,Kirsten,Frazier,Female,2014-12-20,Youth worker
1999998,1965658,April,Griffin,Male,1945-01-13,Youth worker
1999999,1965969,Rachael,Manning,Female,2012-05-10,Youth worker

In [ ]:
table

pyarrow.Table
Index: int64
First Name: string
Last Name: string
Sex: string
Date of birth: string
Job Title: dictionary<values=string, indices=int32, ordered=0>
----
Index: [[131521,133596,133800,133935,134472,...,162575,162972,163351,163538,163732],[544,825,2799,3627,4804,...,31362,31851,32018,32490,32693],...,[1901915,1902122,1902171,1902385,1903752,...,1930783,1931768,1932042,1932298,1932908],[1933720,1933861,1934348,1934526,1935460,...,1964579,1965049,1965107,1965658,1965969]]
First Name: [["Kaitlyn","Shelby","Angel","Anthony","Henry",...,"Jeanne","Levi","Audrey","Judy","Ellen"],["Adrian","Barry","Roberta","Alfred","Audrey",...,"Franklin","Curtis","Carlos","Jenna","Clarence"],...,["Tom","Jared","Laura","Juan","Marilyn",...,"Bonnie","Johnathan","Kylie","Madeline","Megan"],["Sheryl","Janice","Joanna","Douglas","Meredith",...,"Jaclyn","Philip","Kirsten","April","Rachael"]]
Last Name: [["Baxter","Henderson","Wu","Haney","Hatfield",...,"Riley","Mcdaniel","Wise","Oconnell","Potter"],["Mitchell","Jensen","Collier","Kline","Marsh",...,"Rich","Greer","Gilbert","Conner","Merritt"],...,["Butler","Mathews","Morales","Gilbert","Wolf",...,"Snow","Contreras","Larsen","Holland","Fitzpatrick"],["Hill","Sanford","Johnston","Mora","Hoover",...,"Lucas","Cooley","Frazier","Griffin","Manning"]]
Sex: [["Female","Male","Female","Female","Female",...,"Male","Male","Male","Female","Female"],["Male","Female","Male","Female","Male",...,"Female","Male","Male","Male","Female"],...,["Female","Male","Male","Female","Male",...,"Female","Male","Female","Male","Female"],["Female","Male","Male","Male","Female",...,"Female","Female","Female","Male","Female"]]
Date of birth: [["1943-09-24","1919-06-15","1991-02-20","2002-08-05","1975-12-22",...,"1958-01-27","2015-09-17","1924-08-30","1969-07-03","1909-11-08"],["1982-04-05","2021-03-27","1923-08-09","1950-10-18","1934-05-10",...,"1999-11-26","1998-11-20","2017-09-17","2013-02-20","1996-06-06"],...,["2011-04-05","1912-03-16","1955-10-14","1973-08-09","1995-10-03",...,"1942-01-11","2021-05-06","1919-12-29","1960-01-19","1983-09-17"],["1958-01-23","2011-01-31","1964-12-25","1975-01-31","1986-02-13",...,"1946-05-10","1907-11-02","2014-12-20","1945-01-13","2012-05-10"]]
Job Title: [  -- dictionary:
["Academic librarian","Accommodation manager","Accountant, chartered certified","Accountant, chartered management","Accountant, chartered public finance",...,"Water quality scientist","Web designer","Wellsite geologist","Writer","Youth worker"]  -- indices:
[0,0,0,0,0,...,0,0,0,0,0],  -- dictionary:
["Academic librarian","Accommodation manager","Accountant, chartered certified","Accountant, chartered management","Accountant, chartered public finance",...,"Water quality scientist","Web designer","Wellsite geologist","Writer","Youth worker"]  -- indices:
[0,0,0,0,0,...,0,0,0,0,0],...,  -- dictionary:
["Academic librarian","Accommodation manager","Accountant, chartered certified","Accountant, chartered management","Accountant, chartered public finance",...,"Water quality scientist","Web designer","Wellsite geologist","Writer","Youth worker"]  -- indices:
[635,635,635,635,635,...,635,635,635,635,635],  -- dictionary:
["Academic librarian","Accommodation manager","Accountant, chartered certified","Accountant, chartered management","Accountant, chartered public finance",...,"Water quality scientist","Web designer","Wellsite geologist","Writer","Youth worker"]  -- indices:
[635,635,635,635,635,...,635,635,635,635,635]]

1.สร้าง partition file เลือก Index ชื่อ นามสกุล เพศ วันเดือนปีเกิด และ งานที่ทำ โดยกรองในส่วนของ ๋Job Title เป้นหลัก

In [ ]:
dataset = ds.dataset(table)
dataset.to_table(columns=['Index','First Name','Last Name', 'Sex', 'Date of birth', 'Job Title']).to_pandas()

,Index,First Name,Last Name,Sex,Date of birth,Job Title
0,131521,Kaitlyn,Baxter,Female,1943-09-24,Academic librarian
1,133596,Shelby,Henderson,Male,1919-06-15,Academic librarian
2,133800,Angel,Wu,Female,1991-02-20,Academic librarian
3,133935,Anthony,Haney,Female,2002-08-05,Academic librarian
4,134472,Henry,Hatfield,Female,1975-12-22,Academic librarian
...,...,...,...,...,...,...
1999995,1964579,Jaclyn,Lucas,Female,1946-05-10,Youth worker
1999996,1965049,Philip,Cooley,Female,1907-11-02,Youth worker
1999997,1965107,Kirsten,Frazier,Female,2014-12-20,Youth worker
1999998,1965658,April,Griffin,Male,1945-01-13,Youth worker
1999999,1965969,Rachael,Manning,Female,2012-05-10,Youth worker

2.ให้ตรวจสอบตำแหน่งงานที่มีในรายการว่ามีทั้งหมดกี่ตำแหน่งงาน แต่ละตำแหน่งงานมีจำนวนกี่คน

In [ ]:
import pyarrow.compute as pc
grouped_table = table.group_by("Job Title").aggregate(
  [("Index",
  "count",  #count #max #min

  pc.CountOptions(mode="only_valid"))]
)

grouped_table.to_pandas()

     Index_count                             Job Title
0           3234                    Academic librarian
1           3134                 Accommodation manager
2           3185       Accountant, chartered certified
3           3130      Accountant, chartered management
4           3174  Accountant, chartered public finance
..           ...                                   ...
631         3092               Water quality scientist
632         3116                          Web designer
633         2943                    Wellsite geologist
634         3140                                Writer
635         3227                          Youth worker

[636 rows x 2 columns]

3.  กรองข้อมูลโดยแสดงเฉพาะข้อมูลของคนที่เป็นเพศชายและมีตำแหน่งเป็น "Writer" เท่านั้น

In [ ]:
table = pa.Table.from_pandas(df)
print(table)
print("Saving to parquet files...")

# Drop result and table columns
table = table.drop(["User Id", "Index", "First Name", "Email", "Phone", "Date of birth"])
print(table)

pyarrow.Table
Index: int64
User Id: string
First Name: string
Last Name: string
Sex: string
Email: string
Phone: string
Date of birth: string
Job Title: string
----
Index: [[1,2,3,4,5,...,1999996,1999997,1999998,1999999,2000000]]
User Id: [["4defE49671cF860","F89B87bCf8f210b","Cad6052BDd5DEaf","e83E46f80f629CD","60AAc4DcaBcE3b6",...,"AbBE4F3Eb5df843","e71af3E8De63CDF","fAF0618097acD1B","f1FC3346F68DFAb","B04Bb8bE7DA70ba"]]
First Name: [["Sydney","Regina","Pamela","Dave","Ian",...,"Susan","Cole","Ethan","Jordan","Shelley"]]
Last Name: [["Shannon","Lin","Blake","Hoffman","Campos",...,"Ellison","Sherman","Leonard","Waller","Meza"]]
Sex: [["Male","Male","Female","Female","Female",...,"Male","Female","Male","Female","Female"]]
Email: [["tvang@example.net","helen14@example.net","brent05@example.org","munozcraig@example.org","brownevelyn@example.net",...,"yward@example.net","nbarnett@example.org","brett57@example.com","harveykendra@example.com","gamblejohnny@example.net"]]
Phone: [["574-440-1423x9799","001-273-664-2268x90121","927-880-5785x85266","001-147-429-8340x608","166-126-4390",...,"855.222.4135x62040","(130)829-9159x800","514.898.2376x3069","6920274656","+1-765-874-1874"]]
Date of birth: [["2020-07-09","1909-06-20","1964-08-19","2009-02-19","1997-10-02",...,"1913-01-05","1977-04-15","1960-08-14","1911-09-05","1961-11-30"]]
Job Title: [["Technical brewer","Teacher, adult education","Armed forces operational officer","Ship broker","Media planner",...,"Research scientist (maths)","Marketing executive","Photographer","Chartered accountant","Printmaker"]]
Saving to parquet files...
pyarrow.Table
Last Name: string
Sex: string
Job Title: string
----
Last Name: [["Shannon","Lin","Blake","Hoffman","Campos",...,"Ellison","Sherman","Leonard","Waller","Meza"]]
Sex: [["Male","Male","Female","Female","Female",...,"Male","Female","Male","Female","Female"]]
Job Title: [["Technical brewer","Teacher, adult education","Armed forces operational officer","Ship broker","Media planner",...,"Research scientist (maths)","Marketing executive","Photographer","Chartered accountant","Printmaker"]]

In [ ]:
table.to_pandas()

        Last Name     Sex                         Job Title
0         Shannon    Male                  Technical brewer
1             Lin    Male          Teacher, adult education
2           Blake  Female  Armed forces operational officer
3         Hoffman  Female                       Ship broker
4          Campos  Female                     Media planner
...           ...     ...                               ...
1999995   Ellison    Male        Research scientist (maths)
1999996   Sherman  Female               Marketing executive
1999997   Leonard    Male                      Photographer
1999998    Waller  Female              Chartered accountant
1999999      Meza  Female                        Printmaker

[2000000 rows x 3 columns]

In [ ]:
expr1 = pc.field("Sex") == "Male"

In [ ]:
expr2 = pc.field("Job Title") == "Writer"

In [ ]:
filtered_df = table.filter(expr1 & expr2).to_pandas()  #descending

In [ ]:
filtered_df

     Last Name   Sex Job Title
0       Cherry  Male    Writer
1       Melton  Male    Writer
2        Zhang  Male    Writer
3     Harrison  Male    Writer
4      Sellers  Male    Writer
...        ...   ...       ...
1537      Wolf  Male    Writer
1538   Andrade  Male    Writer
1539      Gill  Male    Writer
1540   Maynard  Male    Writer
1541     Kelly  Male    Writer

[1542 rows x 3 columns]